### ISSUE TITLE
Section* が機能していない？

### ISSUE THREAD

**Issue by TsuyoshiShuin** [TsuyoshiShuin/episode#10]
hamada.tex の Section* や Subsection* が機能していないかも

**Comment by TsuyoshiShuin** [comment]
具体的に言うと, main.pdf のp3,p7の" ＊ "はあれで正しい？

**Comment by Okdenn** [comment]
これはたぶん正しくなくて，`*` は不要なのだと思います (本来の LaTeX の小文字 `\section` だと `*` を付けることで番号が出なくなりますが，今回 main.tex で定義した `\Section` はコメントを信じるならそのままで番号は出ないはずなので．

**Comment by MasatakaHamada** [comment]
>これはたぶん正しくなくて，* は不要なのだと思います (本来の LaTeX の小文字 \section だと * を付けることで番号が出なくなりますが，今回 main.tex で定義した \Section はコメントとパッと見のコードを信じるならそのままで番号は出ないはずなので (おそらく濱田さんがクセでやってしまっただけかと)．
>cf. main.tex の l. 25

こちらのご指摘の通りです。これから修正します。
申し訳ありません。
