### ISSUE TITLE
井上さんの読み込みpdfが表示されない

### ISSUE THREAD

**Issue by TsuyoshiShuin** [TsuyoshiShuin/episode#11]
サイズがあってない？

**Comment by TsuyoshiShuin** [comment]
コンパイル時のメッセージ
! LaTeX Error: Cannot determine size of graphic in Inoue_image/i1.xbb (no Bound
ingBox).

l.58 ...degraphics[width=10cm]{Inoue_image/i1.pdf}

**Comment by Okdenn** [comment]
なにでどうコンパイルしているか謎なのでなんともだが，[画像ファイルの取り扱い](http://www.ic.daito.ac.jp/~mizutani/tex/image.html)

**Comment by Okdenn** [comment]
(申し訳ないが最近寝るのが遅くて眠いので今日はドロンです......)(濱田さんを召喚しておきます)

**Comment by TsuyoshiShuin** [comment]
早とちりしました
アドレスが不正で読み込んでなかっただけでした
