### ISSUE TITLE
今井さんの line 88 の label が正しくない？

### ISSUE THREAD

**Issue by TsuyoshiShuin** [TsuyoshiShuin/episode#12]
が修正の仕方もよくわからない
pdf の p14の「問１」のところです

**Comment by TsuyoshiShuin** [comment]
[label = (\arabic*)]
のオプションが謎、
取り除けば問題ないが、意図が分からない

**Comment by Okdenn** [comment]
おそらくなのですが，\item のピリオドを外したかったのではないかと思われます．
正しいコマンドは `[label = {\arabic*.}]` です．最後にピリオドが必要です．
cf. [Arabic enumerating inside an alpha enumerating
](https://tex.stackexchange.com/questions/282172/arabic-enumerating-inside-an-alpha-enumerating)

**Comment by Okdenn** [comment]
もしかしたら `[label = ({\arabic*.})]` のような気がします．たぶん `*` が効きすぎて無限に消してるので {} で囲えば止まる?

**Comment by TsuyoshiShuin** [comment]
\renewcommand{\labelenumi}{(\arabic{enumi})}
を挿入して解決
