### ISSUE TITLE
cls ファイルの文字コードが Shift_JIS

### ISSUE THREAD

**Issue by Okdenn** [TsuyoshiShuin/episode#17]
これはさっきコンパイルして発覚したのですが，manuscript 等が全て UTF-8 なのに対して kyoritu.cls のみ何故か Shift_JIS です．
おそらく代々伝わっているものなので理由があるのだと思いますが，可能なら今後は UTF-8 がいい (少なくとも全体でどっちかに統一したほうがよい) と思います (実際私はコンパイルが通らなかった)．
もしなんらか理由をご存知の方は教えてください．

**Comment by MasatakaHamada** [comment]
eπisode Vol.7 の kyoritu.cls も確認しましたが、やはり Shift-JIS になっていました。理由はわかりませんが、おそらくどこかから引っ張ってきたものなのでしょう。

**Comment by Okdenn** [comment]
なんらか理由があれば原稿を Shift-JIS にするべきなのかもしれませんが，特段理由がないようなら UTF-8 に変換したもの (全行確認してはいないがコンパイル通ってるし大丈夫でしょう) を push しますかね......

**Comment by Okdenn** [comment]
仕事早すぎワロタ (ありがとうございます)
