### ISSUE TITLE
counter が謎

### ISSUE THREAD

**Issue by TsuyoshiShuin** [TsuyoshiShuin/episode#9]
例えば hamada.tex を コンパイルしようとすると,
! LaTeX Error: No counter 'Section' defined.
l.5 \newtheorem{hamadadefi}{定義}[Section]
と出てしまう

**Comment by Okdenn** [comment]
どこでコンパイルしているか謎なので一概には言えない (外してる可能性が高い) が，Section は kouritu.cls (をいじった episode クラス的なにか) ところで定義されていたような??

**Comment by Okdenn** [comment]
main.tex のほうですね，たぶん `Section*` も同様の理由だと思います．
[main.tex@masatakahamada's repository](https://github.com/MasatakaHamada/episode/blob/master/main.tex)

**Comment by MasatakaHamada** [comment]
上のご指摘の通り `Section` などは main.tex でまとめて定義されているので、各個人の tex ファイルをコンパイルしようとするとエラーを吐きます。
